version: '3.8'
services:
  echo-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LOG_REQUESTS=true
      - ECHO_DELAY=1000ms
      - ECHO_CHAOS=5
      - ECHO_HEADER_X_Version=1.2.3
      - ECHO_RATE_LIMIT_RPS=10
      - ECHO_RATE_LIMIT_BURST=20
      - ECHO_HISTORY_SIZE=50
      - ECHO_SSE_TICKER=500ms
      - ECHO_SCENARIO_FILE=/config/scenarios.yaml
    volumes:
      - ./scenarios.yaml:/config/scenarios.yaml