---
version: 2.1

orbs:
  goreleaser: hubci/goreleaser@2.5.0

executors:
  golang:
    docker:
      - image: cimg/go:1.25

jobs:
  build:
    executor: golang
    steps:
      - checkout
      - run: go mod download
      - run: go test ./... -v -race -cover
      - run: go build -o advanced-echo-server cmd/advanced-echo-server

workflows:
  version: 2
  global-entry-slot-notifier:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - goreleaser/release:
          name: test-release
          version: '2.1.0'
          go-version: '1.25'
          dry-run: true
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - goreleaser/release:
          name: release
          version: '2.1.0'
          go-version: '1.25'
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
