version: 2.1

jobs:
  test-and-build:
    docker:
      - image: cimg/go:1.25
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod tidy
      - run:
          name: Run Tests (with race detector)
          command: go test -v -race ./...
      - run:
          name: Static Analysis
          command: |
            go fmt ./...
            go vet ./...
      - run:
          name: Build Binary
          command: |
            mkdir -p dist
            go build -ldflags="-s -w" -o dist/advanced-echo-server ./cmd/advanced-echo-server
      - persist_to_workspace:
          root: dist
          paths:
            - .

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-and-build
